### ISSUE TITLE
Can not save open graph

### ISSUE THREAD

**Issue by nalakawula** [maelstrom-cms/odin#10]
Here the log:
```
[2019-10-08 13:12:50] production.ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1 (SQL: insert into `open_graph_scans` (`title`, `description`, `image`, `url`, `icon`, `website_id`, `updated_at`, `created_at`) values
...
```

Thank you

**Comment by OwenMelbz** [comment]
How long is your description?

**Comment by nalakawula** [comment]
371

**Comment by OwenMelbz** [comment]
I would checkout -> https://blog.spotibo.com/meta-description-length/

That length is far too long for the description, which is why this is throwing an error.

But yes changing it to `text` will allow for longer descriptions

**Comment by nalakawula** [comment]
nice best practice advise.
I will close this issue.

Thank you.

**Comment by OwenMelbz** [comment]
I've added a migration which does cater for longer descriptions so it does throw an error.

But has given me the idea for maybe a warning on the UI saying description/title is too long!
