### ISSUE TITLE
Maybe send a notification if robots.txt file doesn’t exist?

### ISSUE THREAD

**Issue by andrewminion-luminfire** [maelstrom-cms/odin#21]
We’re using this internally to monitor some client sites and noticed that those without a robots.txt result in failed horizon jobs:

```GuzzleHttp\Exception\ClientException: Client error: `GET https://clientname.com/robots.txt` resulted in a `404 Not Found` response:```

I would think the ideal handling is to catch that exception and send a notification that the file doesn’t exist. For now I can just disable robots monitoring on those sites.

**Comment by OwenMelbz** [comment]
Do you definitely have robots.txt monitoring turned off in the settings??

**Comment by andrewminion-luminfire** [comment]
No, robots.txt monitor was turned **on** in the settings for those sites, but I didn’t realize they don’t have an existing robots.txt file.

**Comment by OwenMelbz** [comment]
Okay, so to confirm - is there a problem?

If you do not have a `robots.txt` to monitor, then you should keep the setting turned off, this is only needed if you have a `robots.txt` to track

**Comment by andrewminion-luminfire** [comment]
When you put it that way …no, there’s not really a problem 😊
