### ISSUE TITLE
[Feat Request] Send notifications via Slack?

### ISSUE THREAD

**Issue by andrewminion-luminfire** [maelstrom-cms/odin#22]
We’ve been using this for a while and really appreciate it. However, it would be wonderful if it could send notifications via Slack instead/in addition to email.

**Comment by OwenMelbz** [comment]
Hi,

This is certainly something we'd merge in if a PR came in, however as we don't actively need it for ourselves, it's not something we can spend business hours on developing.

If somebody wanted to contribute the feature then great! however as this isn't a bug - I'll close the ticket, everybody is still welcome to reply to it!
