### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hzema** [maelstrom-cms/odin#26]
I tried to install it with php7.3 and apache not working 

Is there any how to? 

Thanks

**Comment by OwenMelbz** [comment]
Sorry you’ll need to provide more information than “it’s not working”

There is a read me in the repo which explains the process.

If you’ve never set up a Laravel project before, I suggest reading a tutorial on how to do that first as this requires you to know how to do that as it’s a Laravel application.

I’m going to close this issue as it’s not a “bug” but will continue to provide support where I can.

Thanks
