### ISSUE TITLE
Odin Not Working

### ISSUE THREAD

**Issue by faizankhalil007** [maelstrom-cms/odin#28]
Hi,
I am trying to install ODIN on my windows PC and Ubuntu server but it's not getting installed. On my server it kept me redirecting to again and again on the home page and adding public/index.php in URL. On my local machine, it keeps showing phpinfo. can you please let me know where I'm wrong

**Comment by OwenMelbz** [comment]
Hi,

Sorry I’ve not used on Windows so cannot help there.

For Ubuntu you will need to set up your apache/nginx and PHP website correctly, I can’t really help with that either as have never needed to do it.

To debug, can you install a clean Laravel project from  the install guide? https://laravel.com/docs/7.x/installation

Once that is working you should be able to do the same with Odin
