### ISSUE TITLE
Small typo which leads to the compiler to fail.

### ISSUE THREAD

**Issue by PollieDev** [maelstrom-cms/odin#3]
Hey, first of all thanks for making such a tool open source.
Have been trying it out and looks so useful, so thanks for sharing!

When trying to compile for the first time it failed for me. But it seems to be a small typo.
If you have a look at [this file](https://github.com/maelstrom-cms/odin/blob/master/resources/js/components/UptimeReport.js#L3) you'll see that on line 3 you accidently put `''` which assumingly was meant to be `';`. So after changing this it worked like a charm.

**Comment by OwenMelbz** [comment]
Hey thanks for spotting :D

I was hastily trying to sort out some double quotes into singles as PHPStorm had imported using the wrong style!

I've fixed https://github.com/maelstrom-cms/odin/commit/70749fa10ca6129c849984946d3ff9e9cf90524f and is now ready for people!
