### ISSUE TITLE
Consider to add a license

### ISSUE THREAD

**Issue by lcenchew** [maelstrom-cms/odin#33]
According to Github, 
https://choosealicense.com/no-permission/

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

It would be problematic for someone to use your code unless there is an explicit license that allows it.

**Comment by OwenMelbz** [comment]
Hi,

As the read me states, this is just an in-house tool that we've listed as open source incase anybody finds it helpful.

We've no plans to plan specific licensing agreements around it, people can use if people want. Just as if we'd published a recipe for pasta. Use it, don't use, we don't really mind the tool is for us.

Thanks
