### ISSUE TITLE
[PR Question] Installation guide

### ISSUE THREAD

**Issue by TheDutchMC** [maelstrom-cms/odin#41]
Whilst installing Odin I've also written an installation guide (Ubuntu). Is there a place for this on this repo, if so, where would be the most appropriate place for this?

It's a markdown file, if that matters any.

**Comment by OwenMelbz** [comment]
Hey, You could submit it as a PR e.g. `INSTALL-UBUNTU.md` then can review it to help decide what to do.

Thanks :)

**Comment by TheDutchMC** [comment]
PR has been created :)
