### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by soneji** [maelstrom-cms/odin#48]
This is a really cool project! Is there any way this project can be dockerised? I am happy to help with development of this

Thanks in advance :)

**Comment by dweissengruber** [comment]
Hi, you can find a Dockerized version in this pull request: https://github.com/maelstrom-cms/odin/pull/51

**Comment by soneji** [comment]
thanks @dweissengruber

**Comment by soneji** [comment]
@OwenMelbz 
Is there any chance you can setup a docker hub repository for this? As I would like to be able to use a cloud image as opposed to building the docker stuff myself

**Comment by OwenMelbz** [comment]
You’d have to ask @dweissengruber about that, I’ve got no experience in docker I’m afraid sorry

**Comment by soneji** [comment]
I think it’s pretty straightforward to setup here: 
https://docs.docker.com/docker-hub/builds/link-source/

But only someone with administrative access to the repo can do it
